### PR TITLE
Release 4.4.0

### PR DESCRIPTION
**Pull request by takluyver**

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by jakirkham** [comment]
Also does [`noarch: python`]( http://conda-forge.readthedocs.io/en/latest/meta.html#building-noarch-packages ) make sense here?

**Comment by takluyver** [comment]
Probably yes.

**Comment by takluyver** [comment]
@conda-forge-admin, please rerender.

**Comment by takluyver** [comment]
Looks happy now. Anything we should check before merging it?

**Comment by minrk** [comment]
:shipit:

**Comment by jasongrout** [comment]
How long should we give people (including people in restricted sys-admin administered environments) to upgrade from conda 4.2? FYI, rendering this package as noarch makes the package break for conda 4.2.

I switched ipywidgets back to not being noarch because conda 4.3 has been out less than a year,  and I consider a year about the right amount of time to give people to upgrade to 4.3.

**Comment by minrk** [comment]
@jasongrout good question. conda fails with:

> Installing conda-forge::jupyter_core-4.4.0-py_0 requires a minimum conda version of 4.3.

But it certainly would be nicer if the solver had pip's 'Requires-Python' behavior, where it would pick the latest-supported version, rather than picking a version it can't install and then balking. If it still installed but didn't get the latest version, I would have no reservations about requiring 4.3.

I'm not sure how much we can do about it, since `noarch: python` is already starting to spread throughout conda-forge. At some point, one of our dependencies is going to pick up noarch, and at that point there isn't any benefit left to us avoiding it, I think.

One year is only in a month, so I'm okay holding off. I'm also okay following conda-forge as saying "conda forge is now adopting noarch, that means conda 4.3", but this is only implicit now because it is *available*.

@jakirkham thoughts on when conda-forge packages should bump the minimum required conda? Should this be a per-package decision, or is conda-forge officially dropping support for conda 4.2, now that `noarch: python` is available?

**Comment by jasongrout** [comment]
> Installing conda-forge::jupyter_core-4.4.0-py_0 requires a minimum conda version of 4.3.

Huh, I didn't see that in a test environment where this package was being installed as a dependency - it just failed the installation when it couldn't import jupyter_core in the test phase of the installation, with no such error. Perhaps I was testing in an older version of conda 4.2?

@jakirkham - an official decision and announcement would be very helpful to make sure people are aware of the ramifications of moving to noarch.

**Comment by jasongrout** [comment]
> If it still installed but didn't get the latest version, I would have no reservations about requiring 4.3.

Agreed.

**Pull request merged**
