### PR TITLE
MNT: rerender

### LINKED ISSUE #23: @conda-forge-admin please rerender
@conda-forge-admin please rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #23.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #23

### CODE REVIEW

**Comment by xhochy** [comment]
@bollwyvl I don't know the problem with drone but here it works 😕

**Comment by bollwyvl** [comment]
Great! I'll bring over the other changes!

**Comment by bollwyvl** [comment]
Well, it was just the `pywin32` bump: hasn't hurt anybody yet, that I know of. So let's go with it!

**Comment by bollwyvl** [comment]
Looks like the `master` upload build was not triggered on drone... or maybe i'm missing something:

https://cloud.drone.io/conda-forge/jupyter_core-feedstock

**Comment by bollwyvl** [comment]
but lo, ` linux-ppc64le/jupyter_core-4.6.1-py38_0.tar.bz2` appeared on a.o:
https://anaconda.org/conda-forge/jupyter_core/files?version=4.6.1

**Comment by bollwyvl** [comment]
Yup, is running now: https://cloud.drone.io/conda-forge/jupyter_core-feedstock/4

**Comment by xhochy** [comment]
The webhook timed out, I retrigged it.

@bollwyvl ppc64le is uploaded by Travis, not drone.

**Comment by xhochy** [comment]
Opened an issue at https://github.com/conda-forge/conda-forge.github.io/issues/954, @bollwyvl if you come across this again, please also mention it in this issue.

**Comment by bollwyvl** [comment]
Awesome, thanks so much! Might need support on some downstreams in a sec...

**Comment by bollwyvl** [comment]
Presumably this job-which-isn't-yet: https://cloud.drone.io/conda-forge/jupyter_client-feedstock/7

**Pull request merged**
