### PR TITLE
[wip] noarch

### LINKED ISSUE #44: make noarch: python with pywin32-on-windows
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

We could now consider using https://github.com/conda-forge/pywin32-on-windows-feedstock (and `run_constrained`) to get our pin without doing n x m builds. I am a bit torn, as we _have_ occasionally found cross-platform bugs for upstream... but I am also very lazy.

### Installed packages

```shell
pywin32>
```

### Environment info

```shell
windows?
```

### PR DESCRIPTION
**Pull request by minrk**
Challenge is that we need _3_ builds, two for Windows:

- unix: no pywin32
- windows + cpython: pywin32
- windows + pypy: no pywin32 (actually the same as unix)

Trying:

- linux noarch builds depend on cpython and `pywin32-on-windows` to get builds 1 and 2
- windows builds depend on pypy and not pywin32 to get build 3

Need to think a bit how to verify these work (the main thing to accomplish is that the windows + pypy build isn't an installation candidate on Windows + cpython, which would omit the pywin32 dependency)

closes #44

### CODE REVIEW

**Comment by bollwyvl** [comment]
Without having to yank versions, is there something we could do on `pywin32-on-windows` that would help this situation?

> windows + pypy build isn't an installation candidate on Windows + cpython,

Could have `run_constrained` to impossible versions?

> noarch packages can't have selectors. 

It may be clearer (and linter-appeasing) to use redundant jinja `{% if %}` blocks instead of selectors.

**Comment by minrk** [comment]
> is there something we could do on pywin32-on-windows that would help this situation?

A `pywin32-on-windows-cpython` would work for us here.

If pywin32-on-windows encapsulated the pypy condition, too, since pywin32 doesn't work on Windows, that would let us have a single noarch package for jupyter-core and anything with similar pywin32 dependency. Currently, depending on pywin32-on-windows prevents installation with pypy, which may be a _good_ thing for most packages that depend on it (i.e. if you actually _require_ pywin32, you don't support pypy). But packages that work on pypy necessarily must also work without pywin32, as is the case for jupyter-core.

**Comment by bollwyvl** [comment]
No luck over on https://github.com/conda-forge/pywin32-on-windows-feedstock/pull/4 yet...

**Comment by isuruf** [comment]
Why not remove `pywin32` dependency altogether even for windows+cpython?

**Comment by minrk** [comment]
> Why not remove pywin32 dependency altogether even for windows+cpython?

I'm not sure I follow. It _is_ a dependency of the package on that platform.

**Comment by isuruf** [comment]
There is a fallback even for windows+cpython that works when pywin32 is not found right?

**Comment by minrk** [comment]
There is a degraded fallback, yes. So we could do that, I guess, and only use pywin32 if available and hope something else depends on it.

**Pull request closed without merging**
