### PR TITLE
manually start PyPy migration 

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

The dependency resolver bot did not start the pypy3.8/3.9 migration because pywin32 is a parent in the graph. But I think pywin32 is an optional dependency for PyPy, not a hard one. The PR works around the problem by manually adding the migration file.

### CODE REVIEW

**Comment by mattip** [comment]
Any ideas why these three tests are failing to find the srcdir in `shutil.copytree`? Is that something known about pypy, windows, and jupyter_core?
```
FAILED tests/test_command.py::test_argv0 - subprocess.CalledProcessError: Com...
FAILED tests/test_migrate.py::test_migrate_dir - shutil.Error: [('C:\\Users\\...
FAILED tests/test_migrate.py::test_migrate_one - shutil.Error: [('C:\\Users\\...
```

**Comment by blink1073** [comment]
I'm not sure, we only test `pypy` on Ubuntu in [CI](https://github.com/jupyter/jupyter_core/blob/550519504c19b8d7529dad7bdc379e72df14b0b8/.github/workflows/test.yml#L31).

**Comment by bollwyvl** [comment]
yerp: if we could figure out the right `noarch` invocation over on #49, we could save a lot of coal...

**Comment by mattip** [comment]
Outdated, closing

**Pull request closed without merging**
