### PR TITLE
Make noarch: python (ignore pypy)

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/jupyter_core we could:
- go ahead and do this, effectively making this uninstallable with `pypy` on windowst going forward
- investigate some other way to have a `pypy`-only build
 - this will likely get harder to support in the future as conda-forge drops more `pypy`
- do nothing: wait for `pywin32` to unblock the `python312` migration, and deal with whatever it does

**Comment by minrk** [comment]
Can we do a `noarch_platforms` variant list like we do for ipykernel? But with variants:

- cpython
- pypy

and put run_constrained on `- python * *_{{ implementation }}`?

Alternatively, we could have two variants, one with pywin32-on-windows dependency and one without, with the one without penalized by a feature or build offset. Effectively 'preferring' pywin32 on windows, but not requiring it.

**Comment by minrk** [comment]
Given the pypy transition, if this proves difficult, I think it's probably also okay to drop pypy here for new builds for now, and then try to get it back in a later build, if there's a need to keep things moving. LMK if you want a hand to try to get the variants built.

**Pull request closed without merging**
